name: Trigger Render CRON Job

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:        # Allows manual trigger from GitHub Actions tab

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render API Endpoint
        run: |
          curl -X POST https://financeapi-h9vs.onrender.com/api/Finance/PostCronJobTest
